const keysList = [
  {
    key: '`',
    keyUpper: '~',
    keyRu: 'ё',
    keyRuUpper: 'Ё',
    classes: ['key', 'letter', 'Backquote'],
  },
  {
    key: '1',
    keyUpper: '!',
    keyRu: '1',
    keyRuUpper: '!',
    classes: ['key', 'num', 'Digit1'],
  },
  {
    key: '2',
    keyUpper: '@',
    keyRu: '2',
    keyRuUpper: '"',
    classes: ['key', 'num', 'Digit2'],
  },
  {
    key: '3',
    keyUpper: '#',
    keyRu: '3',
    keyRuUpper: '№',
    classes: ['key', 'num', 'Digit3'],
  },
  {
    key: '4',
    keyUpper: '$',
    keyRu: '4',
    keyRuUpper: ';',
    classes: ['key', 'num', 'Digit4'],
  },
  {
    key: '5',
    keyUpper: '%',
    keyRu: '5',
    keyRuUpper: '%',
    classes: ['key', 'num', 'Digit5'],
  },
  {
    key: '6',
    keyUpper: '^',
    keyRu: '6',
    keyRuUpper: ':',
    classes: ['key', 'num', 'Digit6'],
  },
  {
    key: '7',
    keyUpper: '&',
    keyRu: '7',
    keyRuUpper: '?',
    classes: ['key', 'num', 'Digit7'],
  },
  {
    key: '8',
    keyUpper: '*',
    keyRu: '8',
    keyRuUpper: '*',
    classes: ['key', 'num', 'Digit8'],
  },
  {
    key: '9',
    keyUpper: '(',
    keyRu: '9',
    keyRuUpper: '(',
    classes: ['key', 'num', 'Digit9'],
  },
  {
    key: '0',
    keyUpper: ')',
    keyRu: '0',
    keyRuUpper: ')',
    classes: ['key', 'num', 'Digit0'],
  },
  {
    key: '-',
    keyUpper: '_',
    keyRu: '-',
    keyRuUpper: '_',
    classes: ['key', 'num', 'Minus'],
  },
  {
    key: '=',
    keyUpper: '+',
    keyRu: '=',
    keyRuUpper: '+',
    classes: ['key', 'num', 'Equal'],
  },
  {
    key: 'Backspace',
    classes: ['key', 'backspace', 'Backspace'],
  },
  {
    key: 'Tab',
    classes: ['key', 'tab', 'Tab'],
  },
  {
    key: 'q',
    keyUpper: 'Q',
    keyRu: 'й',
    keyRuUpper: 'Й',
    classes: ['key', 'letter', 'KeyQ'],
  },
  {
    key: 'w',
    keyUpper: 'W',
    keyRu: 'ц',
    keyRuUpper: 'Ц',
    classes: ['key', 'letter', 'KeyW'],
  },
  {
    key: 'e',
    keyUpper: 'E',
    keyRu: 'у',
    keyRuUpper: 'У',
    classes: ['key', 'letter', 'KeyE'],
  },
  {
    key: 'r',
    keyUpper: 'R',
    keyRu: 'к',
    keyRuUpper: 'К',
    classes: ['key', 'letter', 'KeyR'],
  },
  {
    key: 't',
    keyUpper: 'T',
    keyRu: 'е',
    keyRuUpper: 'Е',
    classes: ['key', 'letter', 'KeyT'],
  },
  {
    key: 'y',
    keyUpper: 'Y',
    keyRu: 'н',
    keyRuUpper: 'Н',
    classes: ['key', 'letter', 'KeyY'],
  },
  {
    key: 'u',
    keyUpper: 'U',
    keyRu: 'г',
    keyRuUpper: 'Г',
    classes: ['key', 'letter', 'KeyU'],
  },
  {
    key: 'i',
    keyUpper: 'I',
    keyRu: 'ш',
    keyRuUpper: 'Ш',
    classes: ['key', 'letter', 'KeyI'],
  },
  {
    key: 'o',
    keyUpper: 'O',
    keyRu: 'щ',
    keyRuUpper: 'Щ',
    classes: ['key', 'letter', 'KeyO'],
  },
  {
    key: 'p',
    keyUpper: 'P',
    keyRu: 'з',
    keyRuUpper: 'З',
    classes: ['key', 'letter', 'KeyP'],
  },
  {
    key: '[',
    keyUpper: '{',
    keyRu: 'х',
    keyRuUpper: 'Х',
    classes: ['key', 'letter', 'BracketLeft'],
  },
  {
    key: ']',
    keyUpper: '}',
    keyRu: 'ъ',
    keyRuUpper: 'Ъ',
    classes: ['key', 'letter', 'BracketRight'],
  },
  {
    key: '\\',
    keyUpper: '|',
    keyRu: '\\',
    keyRuUpper: '|',
    classes: ['key', 'letter', 'Backslash'],
  },
  {
    key: 'del',
    classes: ['key', 'del', 'Delete'],
  },
  {
    key: 'Caps Lock',
    classes: ['key', 'caps-lock', 'CapsLock'],
  },
  {
    key: 'a',
    keyUpper: 'A',
    keyRu: 'ф',
    keyRuUpper: 'Ф',
    classes: ['key', 'letter', 'KeyA'],
  },
  {
    key: 's',
    keyUpper: 'S',
    keyRu: 'ы',
    keyRuUpper: 'Ы',
    classes: ['key', 'letter', 'KeyS'],
  },
  {
    key: 'd',
    keyUpper: 'D',
    keyRu: 'в',
    keyRuUpper: 'В',
    classes: ['key', 'letter', 'KeyD'],
  },
  {
    key: 'f',
    keyUpper: 'F',
    keyRu: 'а',
    keyRuUpper: 'А',
    classes: ['key', 'letter', 'KeyF'],
  },
  {
    key: 'g',
    keyUpper: 'G',
    keyRu: 'п',
    keyRuUpper: 'П',
    classes: ['key', 'letter', 'KeyG'],
  },
  {
    key: 'h',
    keyUpper: 'H',
    keyRu: 'р',
    keyRuUpper: 'Р',
    classes: ['key', 'letter', 'KeyH'],
  },
  {
    key: 'j',
    keyUpper: 'J',
    keyRu: 'о',
    keyRuUpper: 'О',
    classes: ['key', 'letter', 'KeyJ'],
  },
  {
    key: 'k',
    keyUpper: 'K',
    keyRu: 'л',
    keyRuUpper: 'Л',
    classes: ['key', 'letter', 'KeyK'],
  },
  {
    key: 'l',
    keyUpper: 'L',
    keyRu: 'д',
    keyRuUpper: 'Д',
    classes: ['key', 'letter', 'KeyL'],
  },
  {
    key: ';',
    keyUpper: ':',
    keyRu: 'ж',
    keyRuUpper: 'Ж',
    classes: ['key', 'letter', 'Semicolon'],
  },
  {
    key: "'",
    keyUpper: '"',
    keyRu: 'э',
    keyRuUpper: 'Э',
    classes: ['key', 'letter', 'Quote'],
  },
  {
    key: 'Enter',
    classes: ['key', 'enter', 'Enter'],
  },
  {
    key: 'Shift',
    classes: ['key', 'shift', 'ShiftLeft'],
  },
  {
    key: 'z',
    keyUpper: 'Z',
    keyRu: 'я',
    keyRuUpper: 'Я',
    classes: ['key', 'letter', 'KeyZ'],
  },
  {
    key: 'x',
    keyUpper: 'X',
    keyRu: 'ч',
    keyRuUpper: 'Ч',
    classes: ['key', 'letter', 'KeyX'],
  },
  {
    key: 'c',
    keyUpper: 'C',
    keyRu: 'с',
    keyRuUpper: 'С',
    classes: ['key', 'letter', 'KeyC'],
  },
  {
    key: 'v',
    keyUpper: 'V',
    keyRu: 'м',
    keyRuUpper: 'М',
    classes: ['key', 'letter', 'KeyV'],
  },
  {
    key: 'b',
    keyUpper: 'B',
    keyRu: 'и',
    keyRuUpper: 'И',
    classes: ['key', 'letter', 'KeyB'],
  },
  {
    key: 'n',
    keyUpper: 'N',
    keyRu: 'т',
    keyRuUpper: 'Т',
    classes: ['key', 'letter', 'KeyN'],
  },
  {
    key: 'm',
    keyUpper: 'M',
    keyRu: 'ь',
    keyRuUpper: 'Ь',
    classes: ['key', 'letter', 'KeyM'],
  },
  {
    key: ',',
    keyUpper: '<',
    keyRu: 'б',
    keyRuUpper: 'Б',
    classes: ['key', 'letter', 'Comma'],
  },
  {
    key: '.',
    keyUpper: '>',
    keyRu: 'ю',
    keyRuUpper: 'Ю',
    classes: ['key', 'letter', 'Period'],
  },
  {
    key: '/',
    keyUpper: '?',
    keyRu: '.',
    keyRuUpper: ',',
    classes: ['key', 'letter', 'Slash'],
  },
  {
    key: '\u2191',
    classes: ['key', 'arrow', 'ArrowUp'],
  },
  {
    key: 'Shift',
    classes: ['key', 'shift', 'ShiftRight'],
  },
  {
    key: 'Ctrl',
    classes: ['key', 'lctrl', 'ControlLeft'],
  },
  {
    key: 'Win',
    classes: ['key', 'win', 'MetaLeft'],
  },
  {
    key: 'Alt',
    classes: ['key', 'lalt', 'AltLeft'],
  },
  {
    key: '',
    classes: ['key', 'space', 'Space'],
  },
  {
    key: 'Alt',
    classes: ['key', 'ralt', 'AltRight'],
  },
  {
    key: '\u2190',
    classes: ['key', 'arrow', 'ArrowLeft'],
  },
  {
    key: '\u2193',
    classes: ['key', 'arrow', 'ArrowDown'],
  },
  {
    key: '\u2192',
    classes: ['key', 'arrow', 'ArrowRight'],
  },
  {
    key: 'Ctrl',
    classes: ['key', 'rctrl', 'ControlRight'],
  },
];
export default keysList;
