const keysList = [
    {
        "key": "`",
        "key-upper": "`",
        "key-ru": "ё",
        "key-ru-upper": "`",
        "classes": ["key", "letter"],
    },
    {
        "key": "1",
        "key-upper": "!",
        "classes": ["key", "num"],
    },
    {
        "key": "2",
        "key-upper": "@",
        "classes": ["key", "num"],
    },
    {
        "key": "3",
        "key-upper": "#",
        "classes": ["key", "num"],
    },
    {
        "key": "4",
        "key-upper": "$",
        "classes": ["key", "num"],
    },
    {
        "key": "5",
        "key-upper": "%",
        "classes": ["key", "num"],
    },
    {
        "key": "6",
        "key-upper": "^",
        "classes": ["key", "num"],
    },
    {
        "key": "7",
        "key-upper": "&",
        "classes": ["key", "num"],
    },
    {
        "key": "8",
        "key-upper": "*",
        "classes": ["key", "num"],
    },
    {
        "key": "9",
        "key-upper": "(",
        "classes": ["key", "num"],
    },
    {
        "key": "0",
        "key-upper": ")",
        "classes": ["key", "num"],
    },
    {
        "key": "-",
        "key-upper": "_",
        "classes": ["key", "num"],
    },
    {
        "key": "=",
        "key-upper": "+",
        "classes": ["key", "num"],
    },
    {
        "key": "Backspace",
        "classes": ["key", "backspace"],
    },
    {
        "key": "Tab",
        "classes": ["key", "tab"],
    },
    {
        "key": "q",
        "key-upper": "Q",
        "key-ru": "й",
        "key-ru-upper": "Й",
        "classes": ["key", "letter"],
    },
    {
        "key": "w",
        "key-upper": "W",
        "key-ru": "ц",
        "key-ru-upper": "Ц",
        "classes": ["key", "letter"],
    },
    {
        "key": "e",
        "key-upper": "E",
        "key-ru": "У",
        "key-ru-upper": "У",
        "classes": ["key", "letter"],
    },
    {
        "key": "r",
        "key-upper": "R",
        "key-ru": "к",
        "key-ru-upper": "К",
        "classes": ["key", "letter"],
    },
    {
        "key": "t",
        "key-upper": "T",
        "key-ru": "е",
        "key-ru-upper": "Е",
        "classes": ["key", "letter"],
    },
    {
        "key": "y",
        "key-upper": "Y",
        "key-ru": "н",
        "key-ru-upper": "Н",
        "classes": ["key", "letter"],
    },
    {
        "key": "u",
        "key-upper": "U",
        "key-ru": "г",
        "key-ru-upper": "Г",
        "classes": ["key", "letter"],
    },
    {
        "key": "i",
        "key-upper": "I",
        "key-ru": "ш",
        "key-ru-upper": "Ш",
        "classes": ["key", "letter"],
    },
    {
        "key": "o",
        "key-upper": "O",
        "key-ru": "щ",
        "key-ru-upper": "Щ",
        "classes": ["key", "letter"],
    },
    {
        "key": "p",
        "key-upper": "P",
        "key-ru": "з",
        "key-ru-upper": "З",
        "classes": ["key", "letter"],
    },
    {
        "key": "[",
        "key-upper": "{",
        "key-ru": "х",
        "key-ru-upper": "Х",
        "classes": ["key", "letter"],
    },
    {
        "key": "]",
        "key-upper": "}",
        "key-ru": "ъ",
        "key-ru-upper": "Ъ",
        "classes": ["key", "letter"],
    },
    {
        "key": '\\',
        "key-upper": "|",
        "classes": ["key"],
    },
    {
        "key": "del",
        "classes": ["key", "del"],
    },
    {
        "key": "Caps Lock",
        "classes": ["key", "caps-lock"],
    },
    {
        "key": "a",
        "key-upper": "A",
        "key-ru": "ф",
        "key-ru-upper": "Ф",
        "classes": ["key", "letter"],
    },
    {
        "key": "s",
        "key-upper": "S",
        "key-ru": "ы",
        "key-ru-upper": "Ы",
        "classes": ["key", "letter"],
    },
    {
        "key": "d",
        "key-upper": "D",
        "key-ru": "в",
        "key-ru-upper": "В",
        "classes": ["key", "letter"],
    },
    {
        "key": "f",
        "key-upper": "F",
        "key-ru": "а",
        "key-ru-upper": "А",
        "classes": ["key", "letter"],
    },
    {
        "key": "g",
        "key-upper": "G",
        "key-ru": "п",
        "key-ru-upper": "П",
        "classes": ["key", "letter"],
    },
    {
        "key": "h",
        "key-upper": "H",
        "key-ru": "р",
        "key-ru-upper": "Р",
        "classes": ["key", "letter"],
    },
    {
        "key": "j",
        "key-upper": "J",
        "key-ru": "о",
        "key-ru-upper": "О",
        "classes": ["key", "letter"],
    },
    {
        "key": "k",
        "key-upper": "K",
        "key-ru": "л",
        "key-ru-upper": "Л",
        "classes": ["key", "letter"],
    },
    {
        "key": "l",
        "key-upper": "L",
        "key-ru": "д",
        "key-ru-upper": "Д",
        "classes": ["key", "letter"],
    },
    {
        "key": ";",
        "key-upper": ":",
        "key-ru": "ж",
        "key-ru-upper": "Ж",
        "classes": ["key", "letter"],
    },
    {
        "key": "'",
        "key-upper": '"',
        "key-ru": "э",
        "key-ru-upper": "Э",
        "classes": ["key", "letter"],
    },
    {
        "key": "Enter",
        "classes": ["key", "enter"],
    },
    {
        "key": "Shift",
        "classes": ["key", "lshift"],
    },
    {
        "key": "z",
        "key-upper": "Z",
        "key-ru": "я",
        "key-ru-upper": "Я",
        "classes": ["key", "letter"],
    },
    {
        "key": "x",
        "key-upper": "X",
        "key-ru": "ч",
        "key-ru-upper": "Ч",
        "classes": ["key", "letter"],
    },
    {
        "key": "c",
        "key-upper": "C",
        "key-ru": "с",
        "key-ru-upper": "С",
        "classes": ["key", "letter"],
    },
    {
        "key": "v",
        "key-upper": "V",
        "key-ru": "м",
        "key-ru-upper": "М",
        "classes": ["key", "letter"],
    },
    {
        "key": "b",
        "key-upper": "B",
        "key-ru": "и",
        "key-ru-upper": "И",
        "classes": ["key", "letter"],
    },
    {
        "key": "n",
        "key-upper": "N",
        "key-ru": "т",
        "key-ru-upper": "Т",
        "classes": ["key", "letter"],
    },
    {
        "key": "m",
        "key-upper": "M",
        "key-ru": "ь",
        "key-ru-upper": "Ь",
        "classes": ["key", "letter"],
    },
    {
        "key": ",",
        "key-upper": "<",
        "key-ru": "б",
        "key-ru-upper": "Б",
        "classes": ["key", "letter"],
    },
    {
        "key": ".",
        "key-upper": ">",
        "key-ru": "ю",
        "key-ru-upper": "Ю",
        "classes": ["key", "letter"],
    },
    {
        "key": "/",
        "key-upper": '?',
        "key-ru": ".",
        "key-ru-upper": ",",
        "classes": ["key", "letter"],
    },
    {
        "key": "\u2191",
        "classes": ["key"],
    },
    {
        "key": "Shift",
        "classes": ["key", "rshift"],
    },
    {
        "key": "Ctrl",
        "classes": ["key", "lctrl"],
    },
    {
        "key": "Win",
        "classes": ["key", "win"],
    },
    {
        "key": "Alt",
        "classes": ["key", "lalt"],
    },
    {
        "key": "",
        "classes": ["key", "space"],
    },
    {
        "key": "Alt",
        "classes": ["key", "ralt"],
    },
    {
        "key": "\u2190",
        "classes": ["key"],
    },
    {
        "key": "\u2193",
        "classes": ["key"],
    },
    {
        "key": "\u2192",
        "classes": ["key"],
    },
    {
        "key": "Ctrl",
        "classes": ["key", "rctrl"],
    },
]
export default keysList;